creation_rules:
  - path_regex: .*\.(enc\.)?(yaml|yml|env|txt)$
    encrypted_regex: ".*"
    # Environment age public key (matches age.pubkey)
    age: age10grvhsxrr2gdsd56ad0kcgxr0qh6vgnm0ewks8cyteufqsjeaczqazs6ls
